/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppLinksRouteImport } from './routes/_app/links'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as GoLinkIdRouteImport } from './routes/go/$linkId'
import { Route as AppDatabasesDatabaseIdRouteImport } from './routes/_app/databases/$databaseId'
import { Route as AppPagesPageIdRouteImport } from './routes/_app/pages/$pageId'
import { Route as AppTranscriptsIndexRouteImport } from './routes/_app/transcripts/index'
import { Route as AppTranscriptsTranscriptIdRouteImport } from './routes/_app/transcripts/$transcriptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksRoute = AppLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLinkIdRoute = GoLinkIdRouteImport.update({
  id: '/go/$linkId',
  path: '/go/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDatabasesDatabaseIdRoute = AppDatabasesDatabaseIdRouteImport.update({
  id: '/databases/$databaseId',
  path: '/databases/$databaseId',
  getParentRoute: () => AppRoute,
} as any)
const AppPagesPageIdRoute = AppPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AppRoute,
} as any)
const AppTranscriptsIndexRoute = AppTranscriptsIndexRouteImport.update({
  id: '/transcripts/',
  path: '/transcripts/',
  getParentRoute: () => AppRoute,
} as any)
const AppTranscriptsTranscriptIdRoute =
  AppTranscriptsTranscriptIdRouteImport.update({
    id: '/transcripts/$transcriptId',
    path: '/transcripts/$transcriptId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AppHomeRoute
  '/links': typeof AppLinksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/databases/$databaseId': typeof AppDatabasesDatabaseIdRoute
  '/pages/$pageId': typeof AppPagesPageIdRoute
  '/transcripts/$transcriptId': typeof AppTranscriptsTranscriptIdRoute
  '/transcripts/': typeof AppTranscriptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AppHomeRoute
  '/links': typeof AppLinksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/databases/$databaseId': typeof AppDatabasesDatabaseIdRoute
  '/pages/$pageId': typeof AppPagesPageIdRoute
  '/transcripts/$transcriptId': typeof AppTranscriptsTranscriptIdRoute
  '/transcripts': typeof AppTranscriptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/links': typeof AppLinksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/go/$linkId': typeof GoLinkIdRoute
  '/_app/databases/$databaseId': typeof AppDatabasesDatabaseIdRoute
  '/_app/pages/$pageId': typeof AppPagesPageIdRoute
  '/_app/transcripts/$transcriptId': typeof AppTranscriptsTranscriptIdRoute
  '/_app/transcripts/': typeof AppTranscriptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/login'
    | '/signup'
    | '/home'
    | '/links'
    | '/auth/callback'
    | '/go/$linkId'
    | '/databases/$databaseId'
    | '/pages/$pageId'
    | '/transcripts/$transcriptId'
    | '/transcripts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/login'
    | '/signup'
    | '/home'
    | '/links'
    | '/auth/callback'
    | '/go/$linkId'
    | '/databases/$databaseId'
    | '/pages/$pageId'
    | '/transcripts/$transcriptId'
    | '/transcripts'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/home'
    | '/_app/links'
    | '/auth/callback'
    | '/go/$linkId'
    | '/_app/databases/$databaseId'
    | '/_app/pages/$pageId'
    | '/_app/transcripts/$transcriptId'
    | '/_app/transcripts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GoLinkIdRoute: typeof GoLinkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/links': {
      id: '/_app/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AppLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$linkId': {
      id: '/go/$linkId'
      path: '/go/$linkId'
      fullPath: '/go/$linkId'
      preLoaderRoute: typeof GoLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/databases/$databaseId': {
      id: '/_app/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof AppDatabasesDatabaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pages/$pageId': {
      id: '/_app/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof AppPagesPageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transcripts/': {
      id: '/_app/transcripts/'
      path: '/transcripts'
      fullPath: '/transcripts/'
      preLoaderRoute: typeof AppTranscriptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transcripts/$transcriptId': {
      id: '/_app/transcripts/$transcriptId'
      path: '/transcripts/$transcriptId'
      fullPath: '/transcripts/$transcriptId'
      preLoaderRoute: typeof AppTranscriptsTranscriptIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppLinksRoute: typeof AppLinksRoute
  AppDatabasesDatabaseIdRoute: typeof AppDatabasesDatabaseIdRoute
  AppPagesPageIdRoute: typeof AppPagesPageIdRoute
  AppTranscriptsTranscriptIdRoute: typeof AppTranscriptsTranscriptIdRoute
  AppTranscriptsIndexRoute: typeof AppTranscriptsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppLinksRoute: AppLinksRoute,
  AppDatabasesDatabaseIdRoute: AppDatabasesDatabaseIdRoute,
  AppPagesPageIdRoute: AppPagesPageIdRoute,
  AppTranscriptsTranscriptIdRoute: AppTranscriptsTranscriptIdRoute,
  AppTranscriptsIndexRoute: AppTranscriptsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GoLinkIdRoute: GoLinkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
